repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
        exclude: .*/__init__.py
        id: autoflake

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - args:
          - --profile
          - black
        id: isort

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        language: system
        types_or:
          - python
          - pyi

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - commit
        types:
          - python

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.6.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
